# Generated by Django 4.1 on 2022-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created', 'fullname')},
        ),
    ]
