# Generated by Django 4.1 on 2022-09-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='full_name',
        ),
        migrations.AddField(
            model_name='message',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
