# Generated by Django 4.1.1 on 2022-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_message_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user-images/user-default.png', null=True, upload_to='user-images/'),
        ),
    ]
