# Generated by Django 4.1.1 on 2022-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project-images/default.jpg', null=True, upload_to='project-images/'),
        ),
    ]
