# Generated by Django 4.1.1 on 2022-09-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_image'),
        ('projects', '0009_project_dislikes_project_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Like'), (0, 'Dislike')], null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
