# Generated by Django 4.1.1 on 2022-09-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_image'),
        ('projects', '0011_vote_project_alter_vote_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='owner',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('profile', 'project')},
        ),
    ]
